CANDLEPAIR_HARAMI = 1
CANDLEPAIR_FUKUMI = 2
CANDLEPAIR_GAP = 3
CANDLEPAIR_UPDOW = 4
CANDLEPAIR_DOWNDOW = 5

LINEDIST_ABOVE_FAR = -3
LINEDIST_ABOVE_NEAR = -2
LINEDIST_ABOVE_TOUCHED = -1
LINEDIST_CROSSED = 0 
LINEDIST_BELOW_TOUCHED = 1
LINEDIST_BELOW_NEAR = 2
LINEDIST_BELOW_FAR = 3

LINE_TPTREND = 1
LINE_BTTREND = 2
LINE_MAX = 3
LINE_MIN = 4
