IF NOT EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME='#TABLENAME#' AND XTYPE='U')
	CREATE TABLE #TABLENAME# (
	    [ID] INT NOT NULL,
	    [STARTEP] INT,
	    [ENDEP] INT,
	    [STARTDT] datetime,
	    [ENDDT] datetime,
	    PRIMARY KEY (ID),
	);
