IF NOT EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME='#TABLENAME#' AND XTYPE='U')
	CREATE TABLE #TABLENAME# (
	    [TRANSACTION_NAME] VARCHAR(30) NOT NULL,
	    [RUN_MODE] INT, 
	    [LAST_TRANSACTION_ID] INT,
	    [ACCOUNT_ID] VARCHAR(30),
	    [ENVIRONMENT] VARCHAR(30),
	    PRIMARY KEY (TRANSACTION_NAME, RUN_MODE),
	);